#!/usr/bin/env Rscript
# ==============================================================================
# Merge 2023-2025 Data into Unified Database
# ==============================================================================
#
# Purpose: Merge app/2023_compliance/ and app/2025-24/ into unified app/2023-24-25/
#
# Input:  app/2023_compliance/*.rds (2023 data in 2025 schema)
#         app/2025-24/*.rds (2024-2025 data)
# Output: app/2023-24-25/*.rds (unified 3-season database)
#
# Author: Generated by Claude Code
# Date: 2026-03-07
# ==============================================================================

library(tidyverse)
library(dm)
library(glue)
library(fs)
library(lubridate)

# ==============================================================================
# Configuration
# ==============================================================================

INPUT_2023 <- "app/2023_compliance"
INPUT_2025 <- "app/2025-24"
OUTPUT_DIR <- "app/2023-24-25"

# Create output directory
dir_create(OUTPUT_DIR, recurse = TRUE)

# Initialize validation report
validation_results <- list()
merge_log <- list()

cat("\n")
cat("╔══════════════════════════════════════════════════════════════╗\n")
cat("║  2023-2025 Unified Database Merge                            ║\n")
cat("╚══════════════════════════════════════════════════════════════╝\n")
cat("\n")
cat("Input 2023:  ", INPUT_2023, "\n")
cat("Input 2025:  ", INPUT_2025, "\n")
cat("Output:      ", OUTPUT_DIR, "\n")
cat("\n")

# ==============================================================================
# Helper Functions
# ==============================================================================

# Log merge operation
log_merge <- function(db_name, table_name, rows_2023, rows_2025, rows_merged, notes = "") {
  merge_log[[length(merge_log) + 1]] <<- list(
    database = db_name,
    table = table_name,
    rows_2023 = rows_2023,
    rows_2025 = rows_2025,
    rows_merged = rows_merged,
    notes = notes
  )
}

# Validate row counts
validate_counts <- function(name, expected, actual, allow_dedup = FALSE) {
  if (allow_dedup) {
    if (actual > expected) {
      cat("  ⚠️  ", name, ": ", actual, " rows (expected ≤ ", expected, " with deduplication)\n", sep = "")
      validation_results[[name]] <<- list(status = "WARNING", expected = expected, actual = actual)
      return(FALSE)
    }
  } else {
    if (actual != expected) {
      cat("  ❌ ", name, ": ", actual, " rows (expected ", expected, ")\n", sep = "")
      validation_results[[name]] <<- list(status = "FAIL", expected = expected, actual = actual)
      return(FALSE)
    }
  }
  cat("  ✓ ", name, ": ", actual, " rows\n", sep = "")
  validation_results[[name]] <<- list(status = "PASS", expected = expected, actual = actual)
  return(TRUE)
}

# Validate temporal ordering
validate_temporal <- function(df, name) {
  if ("season" %in% names(df)) {
    seasons <- df %>% distinct(season) %>% pull() %>% sort()
    expected_seasons <- c(2023, 2024, 2025)

    if (!all(seasons %in% expected_seasons)) {
      cat("  ⚠️  ", name, ": Unexpected seasons: ", paste(seasons, collapse = ", "), "\n", sep = "")
      return(FALSE)
    }

    cat("  ✓ ", name, ": Seasons ", paste(seasons, collapse = ", "), "\n", sep = "")
  }
  return(TRUE)
}

# Validate list columns
validate_list_columns <- function(df, name, list_cols) {
  for (col in list_cols) {
    if (col %in% names(df)) {
      if (!is.list(df[[col]])) {
        cat("  ❌ ", name, "$", col, ": Not a list column\n", sep = "")
        return(FALSE)
      }
      if (any(sapply(df[[col]], is.null))) {
        cat("  ⚠️  ", name, "$", col, ": Contains NULL values\n", sep = "")
      }
    }
  }
  return(TRUE)
}

# Merge with preference for non-NA values from 2025
merge_with_priority <- function(df1_2023, df2_2025, key_cols, prefer_2025 = TRUE) {
  if (prefer_2025) {
    # Start with 2025 data (more recent)
    merged <- df2_2025

    # Add 2023 rows not in 2025
    df1_anti <- df1_2023 %>%
      anti_join(df2_2025, by = key_cols)

    merged <- bind_rows(merged, df1_anti)
  } else {
    # Simple union (for temporal data)
    merged <- bind_rows(df1_2023, df2_2025)
  }

  return(merged)
}

# ==============================================================================
# 1. Merge ffa_db.rds
# ==============================================================================

cat("──────────────────────────────────────────────────────────────\n")
cat("📦 Processing ffa_db.rds\n")
cat("──────────────────────────────────────────────────────────────\n")

ffa_db_2023 <- readRDS(file.path(INPUT_2023, "ffa_db.rds"))
ffa_db_2025 <- readRDS(file.path(INPUT_2025, "ffa_db.rds"))

# ──────────────────────────────────────────────────────────────────
# 1.1 ffa_player_ids: Union with missing_player_ids, prefer 2025
# ──────────────────────────────────────────────────────────────────

cat("  ⚙️  ffa_player_ids: Merging with priority to 2025\n")

# Load missing IDs supplement
missing_ids <- readRDS(file.path(INPUT_2023, "missing_player_ids.rds"))

# Start with 2025 (most current)
ffa_player_ids_merged <- ffa_db_2025$ffa_player_ids

# Add 2023 players not in 2025
ffa_player_ids_2023_only <- ffa_db_2023$ffa_player_ids %>%
  anti_join(ffa_player_ids_merged, by = "id")

# Add missing IDs not already present
missing_ids_new <- missing_ids %>%
  anti_join(ffa_player_ids_merged, by = "id") %>%
  anti_join(ffa_player_ids_2023_only, by = "id")

# Combine all
ffa_player_ids_merged <- bind_rows(
  ffa_player_ids_merged,
  ffa_player_ids_2023_only,
  missing_ids_new
)

log_merge("ffa_db", "ffa_player_ids",
          nrow(ffa_db_2023$ffa_player_ids),
          nrow(ffa_db_2025$ffa_player_ids),
          nrow(ffa_player_ids_merged),
          glue("Includes {nrow(missing_ids_new)} from missing_player_ids.rds"))

cat("     ✓ 2023: ", nrow(ffa_db_2023$ffa_player_ids), " players\n", sep = "")
cat("     ✓ 2025: ", nrow(ffa_db_2025$ffa_player_ids), " players\n", sep = "")
cat("     ✓ Missing: ", nrow(missing_ids_new), " players\n", sep = "")
cat("     ✓ Merged: ", nrow(ffa_player_ids_merged), " players\n\n", sep = "")

# ──────────────────────────────────────────────────────────────────
# 1.2 ffa_players: Union with priority to 2025
# ──────────────────────────────────────────────────────────────────

cat("  ⚙️  ffa_players: Merging with priority to 2025\n")

ffa_players_merged <- merge_with_priority(
  ffa_db_2023$ffa_players,
  ffa_db_2025$ffa_players,
  c("id", "pos"),
  prefer_2025 = TRUE
)

log_merge("ffa_db", "ffa_players",
          nrow(ffa_db_2023$ffa_players),
          nrow(ffa_db_2025$ffa_players),
          nrow(ffa_players_merged))

cat("     ✓ Merged: ", nrow(ffa_players_merged), " player-position records\n\n", sep = "")

# ──────────────────────────────────────────────────────────────────
# 1.3 ffa_projtable: Simple union (disjoint seasons)
# ──────────────────────────────────────────────────────────────────

cat("  ⚙️  ffa_projtable: Merging temporal data\n")

ffa_projtable_merged <- bind_rows(
  ffa_db_2023$ffa_projtable,
  ffa_db_2025$ffa_projtable
)

log_merge("ffa_db", "ffa_projtable",
          nrow(ffa_db_2023$ffa_projtable),
          nrow(ffa_db_2025$ffa_projtable),
          nrow(ffa_projtable_merged))

validate_counts("ffa_projtable",
                nrow(ffa_db_2023$ffa_projtable) + nrow(ffa_db_2025$ffa_projtable),
                nrow(ffa_projtable_merged))
validate_temporal(ffa_projtable_merged, "ffa_projtable")

# ──────────────────────────────────────────────────────────────────
# 1.4 ffa_proj_source_points: Simple union
# ──────────────────────────────────────────────────────────────────

cat("  ⚙️  ffa_proj_source_points: Merging temporal data\n")

ffa_proj_source_points_merged <- bind_rows(
  ffa_db_2023$ffa_proj_source_points,
  ffa_db_2025$ffa_proj_source_points
)

log_merge("ffa_db", "ffa_proj_source_points",
          nrow(ffa_db_2023$ffa_proj_source_points),
          nrow(ffa_db_2025$ffa_proj_source_points),
          nrow(ffa_proj_source_points_merged))

validate_counts("ffa_proj_source_points",
                nrow(ffa_db_2023$ffa_proj_source_points) + nrow(ffa_db_2025$ffa_proj_source_points),
                nrow(ffa_proj_source_points_merged))

# ──────────────────────────────────────────────────────────────────
# 1.5 ffa_scrape: Simple union
# ──────────────────────────────────────────────────────────────────

cat("  ⚙️  ffa_scrape: Merging temporal data\n")

ffa_scrape_merged <- bind_rows(
  ffa_db_2023$ffa_scrape,
  ffa_db_2025$ffa_scrape
)

log_merge("ffa_db", "ffa_scrape",
          nrow(ffa_db_2023$ffa_scrape),
          nrow(ffa_db_2025$ffa_scrape),
          nrow(ffa_scrape_merged))

validate_counts("ffa_scrape",
                nrow(ffa_db_2023$ffa_scrape) + nrow(ffa_db_2025$ffa_scrape),
                nrow(ffa_scrape_merged))

# ──────────────────────────────────────────────────────────────────
# 1.6 Rebuild dm object
# ──────────────────────────────────────────────────────────────────

cat("  ⚙️  Rebuilding dm object with constraints\n")

ffa_db_merged <- dm(
  ffa_player_ids = ffa_player_ids_merged,
  ffa_players = ffa_players_merged,
  ffa_projtable = ffa_projtable_merged,
  ffa_proj_source_points = ffa_proj_source_points_merged,
  ffa_scrape = ffa_scrape_merged
) %>%
  # Add primary keys
  dm_add_pk(ffa_player_ids, id) %>%
  dm_add_pk(ffa_players, c(id, pos)) %>%
  dm_add_pk(ffa_projtable, c(season, week, tag, timestamp, avg_type, id, pos)) %>%
  dm_add_pk(ffa_proj_source_points, c(season, week, tag, timestamp, data_src, id, pos)) %>%
  dm_add_pk(ffa_scrape, c(season, week, tag, timestamp)) %>%
  # Add foreign keys (check = FALSE due to known violations)
  dm_add_fk(ffa_players, id, ffa_player_ids, check = FALSE) %>%
  dm_add_fk(ffa_projtable, c(id, pos), ffa_players, check = FALSE) %>%
  dm_add_fk(ffa_projtable, c(season, week, tag, timestamp), ffa_scrape) %>%
  dm_add_fk(ffa_proj_source_points, c(id, pos), ffa_players, check = FALSE) %>%
  dm_add_fk(ffa_proj_source_points, c(season, week, tag, timestamp), ffa_scrape)

# Check constraints
cat("\n  🔍 Examining constraints:\n")
constraint_results <- dm_examine_constraints(ffa_db_merged)
print(constraint_results)

saveRDS(ffa_db_merged, file.path(OUTPUT_DIR, "ffa_db.rds"))
cat("\n  💾 Saved: ", file.path(OUTPUT_DIR, "ffa_db.rds"), "\n\n", sep = "")

# ==============================================================================
# 2. Copy nfl_teams_db.rds (no temporal changes)
# ==============================================================================

cat("──────────────────────────────────────────────────────────────\n")
cat("📦 Processing nfl_teams_db.rds\n")
cat("──────────────────────────────────────────────────────────────\n")

cat("  ⚙️  Using 2025-24 version (league structure unchanged)\n")

file_copy(
  file.path(INPUT_2025, "nfl_teams_db.rds"),
  file.path(OUTPUT_DIR, "nfl_teams_db.rds"),
  overwrite = TRUE
)

log_merge("nfl_teams_db", "nfl_teams", 0,
          nrow(readRDS(file.path(INPUT_2025, "nfl_teams_db.rds"))$nfl_teams),
          nrow(readRDS(file.path(OUTPUT_DIR, "nfl_teams_db.rds"))$nfl_teams),
          "Copied from 2025-24 (no temporal data)")

cat("  💾 Saved: ", file.path(OUTPUT_DIR, "nfl_teams_db.rds"), "\n\n", sep = "")

# ==============================================================================
# 3. Merge nfl_players_db.rds
# ==============================================================================

cat("──────────────────────────────────────────────────────────────\n")
cat("📦 Processing nfl_players_db.rds\n")
cat("──────────────────────────────────────────────────────────────\n")

nfl_players_db_2023 <- readRDS(file.path(INPUT_2023, "nfl_players_db.rds"))
nfl_players_db_2025 <- readRDS(file.path(INPUT_2025, "nfl_players_db.rds"))

# ──────────────────────────────────────────────────────────────────
# 3.1 nfl_players: Union with priority to 2025
# ──────────────────────────────────────────────────────────────────

cat("  ⚙️  nfl_players: Merging with priority to 2025\n")

nfl_players_merged <- merge_with_priority(
  nfl_players_db_2023$nfl_players,
  nfl_players_db_2025$nfl_players,
  "playerId",
  prefer_2025 = TRUE
)

log_merge("nfl_players_db", "nfl_players",
          nrow(nfl_players_db_2023$nfl_players),
          nrow(nfl_players_db_2025$nfl_players),
          nrow(nfl_players_merged))

cat("     ✓ Merged: ", nrow(nfl_players_merged), " players\n\n", sep = "")

# ──────────────────────────────────────────────────────────────────
# 3.2 nfl_player_injury_status: Full union (all snapshots)
# ──────────────────────────────────────────────────────────────────

cat("  ⚙️  nfl_player_injury_status: Merging all temporal snapshots\n")

nfl_player_injury_status_merged <- bind_rows(
  nfl_players_db_2023$nfl_player_injury_status,
  nfl_players_db_2025$nfl_player_injury_status
)

log_merge("nfl_players_db", "nfl_player_injury_status",
          nrow(nfl_players_db_2023$nfl_player_injury_status),
          nrow(nfl_players_db_2025$nfl_player_injury_status),
          nrow(nfl_player_injury_status_merged))

validate_counts("nfl_player_injury_status",
                nrow(nfl_players_db_2023$nfl_player_injury_status) +
                  nrow(nfl_players_db_2025$nfl_player_injury_status),
                nrow(nfl_player_injury_status_merged))

# ──────────────────────────────────────────────────────────────────
# 3.3 Rebuild dm object
# ──────────────────────────────────────────────────────────────────

cat("  ⚙️  Rebuilding dm object\n")

nfl_players_db_merged <- dm(
  nfl_players = nfl_players_merged,
  nfl_player_injury_status = nfl_player_injury_status_merged
) %>%
  dm_add_pk(nfl_players, playerId) %>%
  dm_add_pk(nfl_player_injury_status, c(playerId, timestamp)) %>%
  dm_add_fk(nfl_player_injury_status, playerId, nfl_players)

cat("\n  🔍 Examining constraints:\n")
constraint_results <- dm_examine_constraints(nfl_players_db_merged)
print(constraint_results)

saveRDS(nfl_players_db_merged, file.path(OUTPUT_DIR, "nfl_players_db.rds"))
cat("\n  💾 Saved: ", file.path(OUTPUT_DIR, "nfl_players_db.rds"), "\n\n", sep = "")

# ==============================================================================
# 4. Merge nfl_stats_db.rds (SPECIAL HANDLING)
# ==============================================================================

cat("──────────────────────────────────────────────────────────────\n")
cat("📦 Processing nfl_stats_db.rds\n")
cat("──────────────────────────────────────────────────────────────\n")

nfl_stats_db_2023 <- readRDS(file.path(INPUT_2023, "nfl_stats_db.rds"))
nfl_stats_db_2025 <- readRDS(file.path(INPUT_2025, "nfl_stats_db.rds"))

# ──────────────────────────────────────────────────────────────────
# 4.1 nfl_stat_dictionary: Use 2025 version
# ──────────────────────────────────────────────────────────────────

cat("  ⚙️  nfl_stat_dictionary: Using 2025 version\n")

nfl_stat_dictionary_merged <- nfl_stats_db_2025$nfl_stat_dictionary

log_merge("nfl_stats_db", "nfl_stat_dictionary",
          nrow(nfl_stats_db_2023$nfl_stat_dictionary),
          nrow(nfl_stats_db_2025$nfl_stat_dictionary),
          nrow(nfl_stat_dictionary_merged),
          "Reference data from 2025")

# ──────────────────────────────────────────────────────────────────
# 4.2 nfl_players_points: Simple union
# ──────────────────────────────────────────────────────────────────

cat("  ⚙️  nfl_players_points: Merging temporal data\n")

nfl_players_points_merged <- bind_rows(
  nfl_stats_db_2023$nfl_players_points,
  nfl_stats_db_2025$nfl_players_points
)

log_merge("nfl_stats_db", "nfl_players_points",
          nrow(nfl_stats_db_2023$nfl_players_points),
          nrow(nfl_stats_db_2025$nfl_players_points),
          nrow(nfl_players_points_merged))

validate_counts("nfl_players_points",
                nrow(nfl_stats_db_2023$nfl_players_points) +
                  nrow(nfl_stats_db_2025$nfl_players_points),
                nrow(nfl_players_points_merged))
validate_temporal(nfl_players_points_merged, "nfl_players_points")

# ──────────────────────────────────────────────────────────────────
# 4.3 nfl_players_stats: Simple union
# ──────────────────────────────────────────────────────────────────

cat("  ⚙️  nfl_players_stats: Merging temporal data\n")

nfl_players_stats_merged <- bind_rows(
  nfl_stats_db_2023$nfl_players_stats,
  nfl_stats_db_2025$nfl_players_stats
)

log_merge("nfl_stats_db", "nfl_players_stats",
          nrow(nfl_stats_db_2023$nfl_players_stats),
          nrow(nfl_stats_db_2025$nfl_players_stats),
          nrow(nfl_players_stats_merged))

validate_counts("nfl_players_stats",
                nrow(nfl_stats_db_2023$nfl_players_stats) +
                  nrow(nfl_stats_db_2025$nfl_players_stats),
                nrow(nfl_players_stats_merged))

# ──────────────────────────────────────────────────────────────────
# 4.4 nfl_players_adv_stats: SPECIAL - Incompatible schemas
# ──────────────────────────────────────────────────────────────────

cat("  ⚠️  nfl_players_adv_stats: INCOMPATIBLE SCHEMAS\n")

adv_stats_2023 <- nfl_stats_db_2023$nfl_players_adv_stats
adv_stats_2025 <- nfl_stats_db_2025$nfl_players_adv_stats

# Identify schema differences
common_cols <- intersect(names(adv_stats_2023), names(adv_stats_2025))
cols_2023_only <- setdiff(names(adv_stats_2023), names(adv_stats_2025))
cols_2025_only <- setdiff(names(adv_stats_2025), names(adv_stats_2023))

cat("     • Common columns: ", length(common_cols), "\n", sep = "")
cat("     • 2023 only: ", paste(cols_2023_only, collapse = ", "), "\n", sep = "")
cat("     • 2025 only: ", paste(cols_2025_only, collapse = ", "), "\n", sep = "")

# Union with all columns (creates NAs for missing)
nfl_players_adv_stats_merged <- bind_rows(
  adv_stats_2023,  # Already has schema_version from transform
  adv_stats_2025 %>% mutate(
    schema_version = "2025",
    schema_note = "2025 schema differs from 2023 (see CLAUDE.md)"
  )
)

log_merge("nfl_stats_db", "nfl_players_adv_stats",
          nrow(adv_stats_2023),
          nrow(adv_stats_2025),
          nrow(nfl_players_adv_stats_merged),
          "INCOMPATIBLE: Use schema_version to filter")

validate_counts("nfl_players_adv_stats",
                nrow(adv_stats_2023) + nrow(adv_stats_2025),
                nrow(nfl_players_adv_stats_merged))

cat("     ⚠️  ALWAYS filter by schema_version before analysis\n\n")

# ──────────────────────────────────────────────────────────────────
# 4.5 Rebuild dm object
# ──────────────────────────────────────────────────────────────────

cat("  ⚙️  Rebuilding dm object\n")

nfl_stats_db_merged <- dm(
  nfl_stat_dictionary = nfl_stat_dictionary_merged,
  nfl_players_points = nfl_players_points_merged,
  nfl_players_stats = nfl_players_stats_merged,
  nfl_players_adv_stats = nfl_players_adv_stats_merged
) %>%
  dm_add_pk(nfl_stat_dictionary, statId) %>%
  dm_add_pk(nfl_players_points, c(playerId, season, week)) %>%
  dm_add_pk(nfl_players_stats, c(playerId, season, week, statId)) %>%
  dm_add_pk(nfl_players_adv_stats, c(playerId, season, week)) %>%
  dm_add_fk(nfl_players_stats, statId, nfl_stat_dictionary)

cat("\n  🔍 Examining constraints:\n")
constraint_results <- dm_examine_constraints(nfl_stats_db_merged)
print(constraint_results)

saveRDS(nfl_stats_db_merged, file.path(OUTPUT_DIR, "nfl_stats_db.rds"))
cat("\n  💾 Saved: ", file.path(OUTPUT_DIR, "nfl_stats_db.rds"), "\n\n", sep = "")

# ==============================================================================
# 5. Merge nfl_round_db.rds
# ==============================================================================

cat("──────────────────────────────────────────────────────────────\n")
cat("📦 Processing nfl_round_db.rds\n")
cat("──────────────────────────────────────────────────────────────\n")

nfl_round_db_2023 <- readRDS(file.path(INPUT_2023, "nfl_round_db.rds"))
nfl_round_db_2025 <- readRDS(file.path(INPUT_2025, "nfl_round_db.rds"))

# Get table names from both databases
tables_2023 <- names(nfl_round_db_2023)
tables_2025 <- names(nfl_round_db_2025)
all_tables <- union(tables_2023, tables_2025)

merged_tables <- list()

for (table_name in all_tables) {
  cat("  ⚙️  ", table_name, ": Merging temporal data\n", sep = "")

  df_2023 <- if (table_name %in% tables_2023) nfl_round_db_2023[[table_name]] else tibble()
  df_2025 <- if (table_name %in% tables_2025) nfl_round_db_2025[[table_name]] else tibble()

  merged_tables[[table_name]] <- bind_rows(df_2023, df_2025)

  log_merge("nfl_round_db", table_name,
            nrow(df_2023),
            nrow(df_2025),
            nrow(merged_tables[[table_name]]))

  validate_counts(paste0("nfl_round_db$", table_name),
                  nrow(df_2023) + nrow(df_2025),
                  nrow(merged_tables[[table_name]]))
}

# Rebuild dm object (using schema from 2025 as reference)
cat("\n  ⚙️  Rebuilding dm object\n")

# Check which tables exist and build dm accordingly
nfl_round_db_merged <- dm(!!!merged_tables)

# Add keys based on documented schema
if ("matchups_games" %in% names(nfl_round_db_merged)) {
  nfl_round_db_merged <- nfl_round_db_merged %>%
    dm_add_pk(matchups_games, c(season, week, matchupId))
}

if ("nfl_teams_rosters" %in% names(nfl_round_db_merged)) {
  nfl_round_db_merged <- nfl_round_db_merged %>%
    dm_add_pk(nfl_teams_rosters, c(season, week, teamId, playerId, tag, timestamp))
}

if ("nfl_teams_week_stats" %in% names(nfl_round_db_merged)) {
  nfl_round_db_merged <- nfl_round_db_merged %>%
    dm_add_pk(nfl_teams_week_stats, c(season, week, teamId))
}

if ("nfl_teams_season_stats" %in% names(nfl_round_db_merged)) {
  nfl_round_db_merged <- nfl_round_db_merged %>%
    dm_add_pk(nfl_teams_season_stats, c(season, teamId))
}

cat("\n  🔍 Examining constraints:\n")
constraint_results <- dm_examine_constraints(nfl_round_db_merged)
print(constraint_results)

saveRDS(nfl_round_db_merged, file.path(OUTPUT_DIR, "nfl_round_db.rds"))
cat("\n  💾 Saved: ", file.path(OUTPUT_DIR, "nfl_round_db.rds"), "\n\n", sep = "")

# ==============================================================================
# 6. Merge nfl_recap_db.rds
# ==============================================================================

cat("──────────────────────────────────────────────────────────────\n")
cat("📦 Processing nfl_recap_db.rds\n")
cat("──────────────────────────────────────────────────────────────\n")

nfl_recap_db_2023 <- readRDS(file.path(INPUT_2023, "nfl_recap_db.rds"))
nfl_recap_db_2025 <- readRDS(file.path(INPUT_2025, "nfl_recap_db.rds"))

cat("  ⚙️  Merging recap narratives (with list columns)\n")

# Get all tables from both databases
tables_2023 <- names(nfl_recap_db_2023)
tables_2025 <- names(nfl_recap_db_2025)
all_tables <- union(tables_2023, tables_2025)

merged_recap_tables <- list()

for (table_name in all_tables) {
  cat("  ⚙️  ", table_name, "\n", sep = "")

  df_2023 <- if (table_name %in% tables_2023) nfl_recap_db_2023[[table_name]] else tibble()
  df_2025 <- if (table_name %in% tables_2025) nfl_recap_db_2025[[table_name]] else tibble()

  merged_recap_tables[[table_name]] <- bind_rows(df_2023, df_2025)

  log_merge("nfl_recap_db", table_name,
            nrow(df_2023),
            nrow(df_2025),
            nrow(merged_recap_tables[[table_name]]))

  validate_counts(paste0("nfl_recap_db$", table_name),
                  nrow(df_2023) + nrow(df_2025),
                  nrow(merged_recap_tables[[table_name]]))
}

nfl_recap_db_merged <- dm(!!!merged_recap_tables)

saveRDS(nfl_recap_db_merged, file.path(OUTPUT_DIR, "nfl_recap_db.rds"))
cat("\n  💾 Saved: ", file.path(OUTPUT_DIR, "nfl_recap_db.rds"), "\n\n", sep = "")

# ==============================================================================
# 7. Merge dudes_simulation_db.rds
# ==============================================================================

cat("──────────────────────────────────────────────────────────────\n")
cat("📦 Processing dudes_simulation_db.rds\n")
cat("──────────────────────────────────────────────────────────────\n")

dudes_sim_db_2023 <- readRDS(file.path(INPUT_2023, "dudes_simulation_db.rds"))
dudes_sim_db_2025 <- readRDS(file.path(INPUT_2025, "dudes_simulation_db.rds"))

# ──────────────────────────────────────────────────────────────────
# 7.1 dudes_players_seeds: Merge with list column validation
# ──────────────────────────────────────────────────────────────────

cat("  ⚙️  dudes_players_seeds: Merging with list column validation\n")

dudes_players_seeds_merged <- bind_rows(
  dudes_sim_db_2023$dudes_players_seeds,
  dudes_sim_db_2025$dudes_players_seeds
)

log_merge("dudes_simulation_db", "dudes_players_seeds",
          nrow(dudes_sim_db_2023$dudes_players_seeds),
          nrow(dudes_sim_db_2025$dudes_players_seeds),
          nrow(dudes_players_seeds_merged))

validate_counts("dudes_players_seeds",
                nrow(dudes_sim_db_2023$dudes_players_seeds) +
                  nrow(dudes_sim_db_2025$dudes_players_seeds),
                nrow(dudes_players_seeds_merged))
validate_list_columns(dudes_players_seeds_merged, "dudes_players_seeds", c("seeds"))

# ──────────────────────────────────────────────────────────────────
# 7.2 dudes_players_simulations: Merge with list column validation
# ──────────────────────────────────────────────────────────────────

cat("  ⚙️  dudes_players_simulations: Merging with list column validation\n")

dudes_players_simulations_merged <- bind_rows(
  dudes_sim_db_2023$dudes_players_simulations,
  dudes_sim_db_2025$dudes_players_simulations
)

log_merge("dudes_simulation_db", "dudes_players_simulations",
          nrow(dudes_sim_db_2023$dudes_players_simulations),
          nrow(dudes_sim_db_2025$dudes_players_simulations),
          nrow(dudes_players_simulations_merged))

validate_counts("dudes_players_simulations",
                nrow(dudes_sim_db_2023$dudes_players_simulations) +
                  nrow(dudes_sim_db_2025$dudes_players_simulations),
                nrow(dudes_players_simulations_merged))
validate_list_columns(dudes_players_simulations_merged, "dudes_players_simulations",
                     c("simulations", "simQuantiles"))

# ──────────────────────────────────────────────────────────────────
# 7.3 Rebuild dm object
# ──────────────────────────────────────────────────────────────────

cat("  ⚙️  Rebuilding dm object\n")

dudes_simulation_db_merged <- dm(
  dudes_players_seeds = dudes_players_seeds_merged,
  dudes_players_simulations = dudes_players_simulations_merged
) %>%
  dm_add_pk(dudes_players_seeds, c(season, week, id, playerId, pos, simType)) %>%
  dm_add_pk(dudes_players_simulations, c(season, week, id, playerId, pos, simType))

cat("\n  🔍 Examining constraints:\n")
constraint_results <- dm_examine_constraints(dudes_simulation_db_merged)
print(constraint_results)

saveRDS(dudes_simulation_db_merged, file.path(OUTPUT_DIR, "dudes_simulation_db.rds"))
cat("\n  💾 Saved: ", file.path(OUTPUT_DIR, "dudes_simulation_db.rds"), "\n\n", sep = "")

# ==============================================================================
# 8. Generate comprehensive reports
# ==============================================================================

cat("──────────────────────────────────────────────────────────────\n")
cat("📊 Generating merge reports\n")
cat("──────────────────────────────────────────────────────────────\n")

# Convert merge log to data frame for reporting
merge_log_df <- bind_rows(merge_log)

# ──────────────────────────────────────────────────────────────────
# 8.1 MERGE_REPORT.md
# ──────────────────────────────────────────────────────────────────

merge_report <- c(
  "# 2023-2025 Unified Database Merge Report",
  "",
  paste("**Date:**", Sys.time()),
  paste("**Input 2023:**", INPUT_2023),
  paste("**Input 2025:**", INPUT_2025),
  paste("**Output:**", OUTPUT_DIR),
  "",
  "---",
  "",
  "## Executive Summary",
  "",
  "Successfully merged 2023-2025 Fantasy Football data into unified databases.",
  glue("Total tables merged: {nrow(merge_log_df)}"),
  glue("Total rows in output: {format(sum(merge_log_df$rows_merged), big.mark=',')}"),
  "",
  "### Databases Created",
  "",
  "| Database | Status | Tables | Notes |",
  "|----------|--------|--------|-------|",
  "| ffa_db.rds | ✅ Merged | 5 | Includes missing_player_ids supplement |",
  "| nfl_teams_db.rds | ✅ Copied | 2 | From 2025-24 (no temporal changes) |",
  "| nfl_players_db.rds | ✅ Merged | 2 | All temporal snapshots preserved |",
  "| nfl_stats_db.rds | ⚠️ Partial | 4 | Incompatible adv_stats schemas |",
  "| nfl_round_db.rds | ✅ Merged | 4+ | All matchup and roster data |",
  "| nfl_recap_db.rds | ✅ Merged | 1+ | Narrative data with list columns |",
  "| dudes_simulation_db.rds | ✅ Merged | 2 | List columns validated |",
  "",
  "---",
  "",
  "## Detailed Merge Statistics",
  "",
  "| Database | Table | 2023 Rows | 2025 Rows | Merged Rows | Notes |",
  "|----------|-------|-----------|-----------|-------------|-------|"
)

for (i in seq_len(nrow(merge_log_df))) {
  row <- merge_log_df[i, ]
  merge_report <- c(
    merge_report,
    sprintf("| %s | %s | %s | %s | %s | %s |",
            row$database,
            row$table,
            format(row$rows_2023, big.mark = ","),
            format(row$rows_2025, big.mark = ","),
            format(row$rows_merged, big.mark = ","),
            row$notes)
  )
}

merge_report <- c(
  merge_report,
  "",
  "---",
  "",
  "## Validation Results",
  "",
  "| Test | Status | Expected | Actual |",
  "|------|--------|----------|--------|"
)

for (name in names(validation_results)) {
  result <- validation_results[[name]]
  status_icon <- switch(result$status,
                       "PASS" = "✅",
                       "WARNING" = "⚠️",
                       "FAIL" = "❌")
  merge_report <- c(
    merge_report,
    sprintf("| %s | %s | %s | %s |",
            name,
            status_icon,
            format(result$expected, big.mark = ","),
            format(result$actual, big.mark = ","))
  )
}

merge_report <- c(
  merge_report,
  "",
  "---",
  "",
  "## Known Issues & Limitations",
  "",
  "### 1. nfl_players_adv_stats Schema Incompatibility",
  "",
  "**Status:** ⚠️ INCOMPATIBLE",
  "",
  "The `nfl_players_adv_stats` table has fundamentally different schemas:",
  "",
  "- **2023 columns:** percentRostered, targets, redzoneTargets, etc.",
  "- **2025 columns:** transactionBuysellAdd, leaguesOwned, avgPointsAgainst, etc.",
  "",
  "**Mitigation:**",
  "- Added `schema_version` column ('2023' or '2025')",
  "- ALWAYS filter by `schema_version` before analysis",
  "- Use stable columns like `averageDraftPosition` for cross-season comparisons",
  "",
  "**Example:**",
  "```r",
  "# ❌ DON'T DO THIS",
  "adv_stats %>% summarise(avg_rostered = mean(percentRostered))",
  "",
  "# ✅ DO THIS",
  "adv_stats %>%",
  "  filter(schema_version == '2023') %>%",
  "  summarise(avg_rostered = mean(percentRostered))",
  "```",
  "",
  "### 2. Foreign Key Violations",
  "",
  "Some players in `ffa_players` are not present in `ffa_player_ids`.",
  "",
  "**Mitigation:**",
  "- FK constraints set with `check = FALSE`",
  "- Documented in FK_VIOLATIONS.md",
  "- Use defensive joins: `left_join()` instead of `inner_join()`",
  "",
  "### 3. NA Values in New Columns",
  "",
  "Columns added in 2024+ are NA for 2023 data:",
  "- `ffa_player_ids`: `gsis_id`, `sleeper_id`",
  "- `nfl_players`: `lastNoteTimestamp`",
  "",
  "**Impact:** Use defensive coding when accessing these columns",
  "",
  "```r",
  "# Check before using",
  "if (!is.na(player_ids$gsis_id)) {",
  "  # Use gsis_id",
  "}",
  "```",
  "",
  "---",
  "",
  "## Cross-Season Analysis Guidelines",
  "",
  "### Safe Queries Across All Seasons",
  "",
  "These columns are **stable** across 2023-2025:",
  "",
  "**ffa_db.rds:**",
  "- `ffa_player_ids`: id, nfl_id, stats_id, espn_id",
  "- `ffa_projtable`: season, week, id, pos, points, sd_pts, floor, ceiling, rank",
  "",
  "**nfl_players_db.rds:**",
  "- `nfl_players`: playerId, name, position, nflTeamAbbr",
  "",
  "**nfl_stats_db.rds:**",
  "- `nfl_players_points`: playerId, season, week, pts",
  "- `nfl_players_stats`: playerId, season, week, statId, value",
  "- `nfl_players_adv_stats`: averageDraftPosition (cross-season safe)",
  "",
  "### Example: Player Performance 2023-2025",
  "",
  "```r",
  "# Load unified database",
  "stats_db <- readRDS('app/2023-24-25/nfl_stats_db.rds')",
  "",
  "# Safe cross-season query",
  "player_history <- stats_db$nfl_players_points %>%",
  "  filter(playerId == '4046') %>%  # Christian McCaffrey",
  "  group_by(season) %>%",
  "  summarise(",
  "    total_points = sum(pts),",
  "    avg_points = mean(pts),",
  "    weeks_played = n()",
  "  ) %>%",
  "  arrange(season)",
  "```",
  "",
  "---",
  "",
  "## File Sizes",
  "",
  paste("| File | Size | 2023 | 2025 |"),
  paste("|------|------|------|------|")
)

# Add file sizes
all_files <- c("ffa_db.rds", "nfl_teams_db.rds", "nfl_players_db.rds",
               "nfl_stats_db.rds", "nfl_round_db.rds", "nfl_recap_db.rds",
               "dudes_simulation_db.rds")

for (file in all_files) {
  merged_size <- file_size(file.path(OUTPUT_DIR, file))
  size_2023 <- if (file_exists(file.path(INPUT_2023, file))) {
    format(file_size(file.path(INPUT_2023, file)), units = "auto")
  } else {
    "N/A"
  }
  size_2025 <- if (file_exists(file.path(INPUT_2025, file))) {
    format(file_size(file.path(INPUT_2025, file)), units = "auto")
  } else {
    "N/A"
  }

  merge_report <- c(
    merge_report,
    sprintf("| %s | %s | %s | %s |",
            file,
            format(merged_size, units = "auto"),
            size_2023,
            size_2025)
  )
}

merge_report <- c(
  merge_report,
  "",
  "---",
  "",
  "## Next Steps",
  "",
  "1. **Review this report** for any validation warnings",
  "2. **Check FK_VIOLATIONS.md** for detailed FK issues",
  "3. **Test cross-season queries** using examples above",
  "4. **Update analysis scripts** to use unified database",
  "",
  "## Usage",
  "",
  "```r",
  "# Load unified databases",
  "ffa_db <- readRDS('app/2023-24-25/ffa_db.rds')",
  "stats_db <- readRDS('app/2023-24-25/nfl_stats_db.rds')",
  "",
  "# Verify season coverage",
  "ffa_db$ffa_projtable %>% distinct(season) %>% arrange(season)",
  "# Should show: 2023, 2024, 2025",
  "",
  "# Cross-season analysis",
  "ffa_db$ffa_projtable %>%",
  "  filter(id == '13589') %>%  # Josh Allen",
  "  select(season, week, points, rank) %>%",
  "  arrange(season, week)",
  "```",
  "",
  "---",
  "",
  paste("**Generated by:** merge_unified_database.R"),
  paste("**Timestamp:**", Sys.time())
)

writeLines(merge_report, file.path(OUTPUT_DIR, "MERGE_REPORT.md"))
cat("  💾 Saved: MERGE_REPORT.md\n")

# ──────────────────────────────────────────────────────────────────
# 8.2 README.md
# ──────────────────────────────────────────────────────────────────

readme_content <- c(
  "# Unified 2023-2025 Fantasy Football Database",
  "",
  "> **Three seasons of Fantasy Football data in unified dm-based databases**",
  ">",
  paste("> Created:", Sys.time()),
  "",
  "---",
  "",
  "## Overview",
  "",
  "This directory contains **unified databases** spanning **three NFL seasons (2023, 2024, 2025)**.",
  "",
  "### Why This Exists",
  "",
  "Previously, data was split across two folders:",
  "- `app/2023_compliance/` - Season 2023 (transformed to 2025 schema)",
  "- `app/2025-24/` - Seasons 2024-2025 (production format)",
  "",
  "This unified dataset enables:",
  "- ✅ Cross-season analysis without managing multiple data sources",
  "- ✅ Single source of truth for historical and current data",
  "- ✅ Simplified analytical workflows",
  "",
  "---",
  "",
  "## Quick Start",
  "",
  "```r",
  "library(tidyverse)",
  "library(dm)",
  "",
  "# Load unified databases",
  "ffa_db <- readRDS('app/2023-24-25/ffa_db.rds')",
  "stats_db <- readRDS('app/2023-24-25/nfl_stats_db.rds')",
  "",
  "# Verify season coverage",
  "ffa_db$ffa_projtable %>%",
  "  distinct(season) %>%",
  "  arrange(season)",
  "# Output: 2023, 2024, 2025",
  "",
  "# Example: Player performance across all 3 seasons",
  "josh_allen_history <- ffa_db$ffa_projtable %>%",
  "  filter(id == '13589', tag == 'final') %>%",
  "  group_by(season, week) %>%",
  "  filter(timestamp == max(timestamp)) %>%",
  "  ungroup() %>%",
  "  select(season, week, points, rank, tier)",
  "```",
  "",
  "---",
  "",
  "## Database Files",
  "",
  "| File | Tables | Description |",
  "|------|--------|-------------|",
  "| **ffa_db.rds** | 5 | Fantasy Football Analytics (projections, player IDs) |",
  "| **nfl_teams_db.rds** | 2 | League teams and owners |",
  "| **nfl_players_db.rds** | 2 | NFL players and injury status |",
  "| **nfl_stats_db.rds** | 4 | Player statistics and points |",
  "| **nfl_round_db.rds** | 4+ | Matchups, rosters, team stats |",
  "| **nfl_recap_db.rds** | 1+ | Game narratives and recaps |",
  "| **dudes_simulation_db.rds** | 2 | Monte Carlo simulation data |",
  "",
  "---",
  "",
  "## Important Notes",
  "",
  "### ⚠️ Schema Incompatibility: nfl_players_adv_stats",
  "",
  "The `nfl_players_adv_stats` table has **incompatible schemas** between 2023 and 2025:",
  "",
  "- **2023:** percentRostered, targets, redzoneTargets, etc.",
  "- **2025:** transactionBuysellAdd, leaguesOwned, avgPointsAgainst, etc.",
  "",
  "**Always filter by `schema_version`:**",
  "",
  "```r",
  "# Get 2023 advanced stats",
  "adv_stats_2023 <- stats_db$nfl_players_adv_stats %>%",
  "  filter(schema_version == '2023')",
  "",
  "# Get 2025 advanced stats",
  "adv_stats_2025 <- stats_db$nfl_players_adv_stats %>%",
  "  filter(schema_version == '2025')",
  "",
  "# For cross-season analysis, use stable columns:",
  "adp_trends <- stats_db$nfl_players_adv_stats %>%",
  "  select(playerId, season, week, averageDraftPosition) %>%",
  "  arrange(playerId, season, week)",
  "```",
  "",
  "### 📝 Foreign Key Violations",
  "",
  "Some FK constraints are documented as violations (see `FK_VIOLATIONS.md`).",
  "",
  "**Best practice:** Use `left_join()` instead of `inner_join()` when joining across databases.",
  "",
  "### 🔍 NA Values in New Columns",
  "",
  "Columns added in 2024+ are NA for 2023 data:",
  "- `ffa_player_ids`: `gsis_id`, `sleeper_id`",
  "- `nfl_players`: `lastNoteTimestamp`",
  "",
  "Use defensive coding:",
  "",
  "```r",
  "# Check before using new columns",
  "player_ids %>%",
  "  filter(!is.na(gsis_id)) %>%",
  "  # Use gsis_id safely",
  "```",
  "",
  "---",
  "",
  "## Stable Columns for Cross-Season Analysis",
  "",
  "These columns are **guaranteed consistent** across all three seasons:",
  "",
  "### ffa_db.rds",
  "- `ffa_player_ids`: id, nfl_id, stats_id, espn_id",
  "- `ffa_projtable`: season, week, id, pos, points, sd_pts, floor, ceiling, rank",
  "",
  "### nfl_players_db.rds",
  "- `nfl_players`: playerId, name, position, nflTeamAbbr",
  "",
  "### nfl_stats_db.rds",
  "- `nfl_players_points`: playerId, season, week, pts",
  "- `nfl_players_stats`: playerId, season, week, statId, value",
  "",
  "---",
  "",
  "## Common Patterns",
  "",
  "### Pattern 1: Season-over-season player comparison",
  "",
  "```r",
  "compare_seasons <- function(player_id) {",
  "  stats_db$nfl_players_points %>%",
  "    filter(playerId == player_id) %>%",
  "    group_by(season) %>%",
  "    summarise(",
  "      total_pts = sum(pts),",
  "      avg_pts = mean(pts),",
  "      games = n()",
  "    )",
  "}",
  "",
  "# Example: Christian McCaffrey",
  "compare_seasons('4046')",
  "```",
  "",
  "### Pattern 2: Projection accuracy over time",
  "",
  "```r",
  "projection_accuracy <- ffa_db$ffa_projtable %>%",
  "  filter(tag == 'final', avg_type == 'robust') %>%",
  "  group_by(season, week) %>%",
  "  filter(timestamp == max(timestamp)) %>%",
  "  ungroup() %>%",
  "  left_join(",
  "    stats_db$nfl_players_points,",
  "    by = c('id' = 'playerId', 'season', 'week')",
  "  ) %>%",
  "  mutate(error = abs(points - pts)) %>%",
  "  group_by(season, pos) %>%",
  "  summarise(mae = mean(error, na.rm = TRUE))",
  "```",
  "",
  "### Pattern 3: Multi-season simulation analysis",
  "",
  "```r",
  "sim_db <- readRDS('app/2023-24-25/dudes_simulation_db.rds')",
  "",
  "# Compare simulation types across seasons",
  "sim_performance <- sim_db$dudes_players_simulations %>%",
  "  unnest_wider(simQuantiles) %>%",
  "  group_by(season, simType) %>%",
  "  summarise(",
  "    median_projection = median(q50),",
  "    p90_spread = mean(q95 - q05)",
  "  )",
  "```",
  "",
  "---",
  "",
  "## Documentation",
  "",
  "- **MERGE_REPORT.md** - Detailed merge statistics and validation results",
  "- **FK_VIOLATIONS.md** - Known foreign key constraint violations",
  "- **app_DATAMODEL.md** - Complete schema reference (in parent directory)",
  "- **CLAUDE.md** - Historical compatibility notes (in parent directory)",
  "",
  "---",
  "",
  "## Troubleshooting",
  "",
  "### \"Player not found in ffa_player_ids\"",
  "",
  "Some players in projections don't have ID mappings. Use left joins:",
  "",
  "```r",
  "# ❌ May drop players",
  "inner_join(ffa_players, ffa_player_ids, by = 'id')",
  "",
  "# ✅ Preserves all players",
  "left_join(ffa_players, ffa_player_ids, by = 'id')",
  "```",
  "",
  "### \"Column not found in 2023 data\"",
  "",
  "Use defensive selection:",
  "",
  "```r",
  "# Check column existence",
  "safe_select <- function(df, cols) {",
  "  available_cols <- intersect(cols, names(df))",
  "  select(df, all_of(available_cols))",
  "}",
  "",
  "# Use",
  "safe_select(adv_stats, c('playerId', 'gsis_id', 'percentRostered'))",
  "```",
  "",
  "---",
  "",
  "## Maintenance",
  "",
  "To regenerate this unified database:",
  "",
  "```bash",
  "# From project root",
  "Rscript merge_unified_database.R",
  "```",
  "",
  "This will:",
  "1. Read from `app/2023_compliance/` and `app/2025-24/`",
  "2. Merge all databases following documented strategies",
  "3. Validate row counts and constraints",
  "4. Generate comprehensive reports",
  "",
  "---",
  "",
  paste("**Last Updated:**", Sys.time())
)

writeLines(readme_content, file.path(OUTPUT_DIR, "README.md"))
cat("  💾 Saved: README.md\n")

# ──────────────────────────────────────────────────────────────────
# 8.3 FK_VIOLATIONS.md
# ──────────────────────────────────────────────────────────────────

fk_violations <- c(
  "# Foreign Key Violations",
  "",
  paste("**Analysis Date:**", Sys.time()),
  "",
  "---",
  "",
  "## Overview",
  "",
  "This document lists known Foreign Key (FK) constraint violations in the unified database.",
  "",
  "### Why Violations Exist",
  "",
  "1. **Data source discrepancies:** ffanalytics may scrape player projections before",
  "   the player exists in the NFL API",
  "2. **Manual data entry:** Some player IDs are added manually (see `missing_player_ids.rds`)",
  "3. **Legacy data:** Historical data may have incomplete ID mapping",
  "",
  "---",
  "",
  "## ffa_db.rds Violations",
  "",
  "### ffa_players → ffa_player_ids",
  "",
  "**Issue:** Some players in `ffa_players` don't have entries in `ffa_player_ids`.",
  "",
  "**Impact:** Cannot map these players to external systems (NFL API, ESPN, CBS, etc.)",
  "",
  "**Mitigation:**",
  "1. Use `missing_player_ids.rds` as supplement",
  "2. Use `left_join()` instead of `inner_join()`",
  "3. Accept NA values for external IDs",
  "",
  "**Example:**",
  "```r",
  "# Load supplement",
  "missing_ids <- readRDS('app/2023_compliance/missing_player_ids.rds')",
  "",
  "# Consolidate",
  "all_ids <- bind_rows(",
  "  ffa_db$ffa_player_ids,",
  "  missing_ids",
  ")",
  "",
  "# Safe join",
  "ffa_db$ffa_players %>%",
  "  left_join(all_ids, by = 'id')  # Preserves unmatched players",
  "```",
  "",
  "### ffa_projtable → ffa_players",
  "",
  "**Issue:** Some projections reference (id, pos) combinations not in `ffa_players`.",
  "",
  "**Impact:** Cannot get full player metadata for these projections.",
  "",
  "**Mitigation:** Use left joins and accept partial metadata",
  "",
  "```r",
  "ffa_db$ffa_projtable %>%",
  "  left_join(ffa_db$ffa_players, by = c('id', 'pos')) %>%",
  "  # first_name, last_name may be NA for some rows",
  "  filter(!is.na(first_name))  # Or keep NAs and handle downstream",
  "```",
  "",
  "---",
  "",
  "## Finding Violation Details",
  "",
  "### Identify missing player IDs",
  "",
  "```r",
  "# Players without ID mapping",
  "unmapped_players <- ffa_db$ffa_players %>%",
  "  anti_join(ffa_db$ffa_player_ids, by = 'id') %>%",
  "  select(id, first_name, last_name, team, position) %>%",
  "  arrange(last_name, first_name)",
  "",
  "# Count by position",
  "unmapped_players %>%",
  "  count(position, sort = TRUE)",
  "```",
  "",
  "### Check projection coverage",
  "",
  "```r",
  "# Projections without player metadata",
  "orphan_projections <- ffa_db$ffa_projtable %>%",
  "  anti_join(ffa_db$ffa_players, by = c('id', 'pos')) %>%",
  "  distinct(id, pos) %>%",
  "  arrange(pos, id)",
  "```",
  "",
  "---",
  "",
  "## Best Practices",
  "",
  "1. **Always use left joins** when connecting ffa tables",
  "2. **Check for NAs** after joins and decide handling strategy",
  "3. **Use missing_player_ids.rds** as supplemental data source",
  "4. **Document assumptions** when dropping NA rows",
  "",
  "### Good Example",
  "",
  "```r",
  "# Defensive join with clear NA handling",
  "analysis_data <- ffa_db$ffa_projtable %>%",
  "  filter(season == 2025, week == 17) %>%",
  "  left_join(ffa_db$ffa_players, by = c('id', 'pos')) %>%",
  "  mutate(",
  "    player_label = case_when(",
  "      !is.na(first_name) ~ glue('{first_name} {last_name}'),",
  "      TRUE ~ glue('Unknown Player {id}')",
  "    )",
  "  )",
  "```",
  "",
  "### Bad Example",
  "",
  "```r",
  "# ❌ Silent data loss",
  "analysis_data <- ffa_db$ffa_projtable %>%",
  "  inner_join(ffa_db$ffa_players, by = c('id', 'pos'))  # Drops unmapped players",
  "```",
  "",
  "---",
  "",
  paste("**Document Version:**", Sys.time())
)

writeLines(fk_violations, file.path(OUTPUT_DIR, "FK_VIOLATIONS.md"))
cat("  💾 Saved: FK_VIOLATIONS.md\n\n")

# ==============================================================================
# 9. Final Summary
# ==============================================================================

cat("╔══════════════════════════════════════════════════════════════╗\n")
cat("║  ✅ MERGE COMPLETE                                           ║\n")
cat("╚══════════════════════════════════════════════════════════════╝\n")
cat("\n")
cat("📁 Output directory: ", OUTPUT_DIR, "\n")
cat("\n")
cat("Databases created:\n")
cat("  ✓ ffa_db.rds (5 tables, 3 seasons)\n")
cat("  ✓ nfl_teams_db.rds (2 tables, from 2025)\n")
cat("  ✓ nfl_players_db.rds (2 tables, 3 seasons)\n")
cat("  ✓ nfl_stats_db.rds (4 tables, 3 seasons)\n")
cat("  ✓ nfl_round_db.rds (4+ tables, 3 seasons)\n")
cat("  ✓ nfl_recap_db.rds (1+ tables, 3 seasons)\n")
cat("  ✓ dudes_simulation_db.rds (2 tables, 3 seasons)\n")
cat("\n")
cat("Documentation created:\n")
cat("  📖 README.md (user guide)\n")
cat("  📊 MERGE_REPORT.md (technical details)\n")
cat("  ⚠️  FK_VIOLATIONS.md (known issues)\n")
cat("\n")

# Count validation results
passed <- sum(sapply(validation_results, function(x) x$status == "PASS"))
warnings <- sum(sapply(validation_results, function(x) x$status == "WARNING"))
failed <- sum(sapply(validation_results, function(x) x$status == "FAIL"))

cat("Validation summary:\n")
cat(glue("  ✅ Passed: {passed}"), "\n")
if (warnings > 0) cat(glue("  ⚠️  Warnings: {warnings}"), "\n")
if (failed > 0) cat(glue("  ❌ Failed: {failed}"), "\n")
cat("\n")

if (failed > 0) {
  cat("⚠️  Some validations failed. Review MERGE_REPORT.md for details.\n\n")
} else {
  cat("✨ All validations passed!\n\n")
}

cat("Next steps:\n")
cat("  1. Review MERGE_REPORT.md for validation details\n")
cat("  2. Check FK_VIOLATIONS.md for known data quality issues\n")
cat("  3. Test cross-season queries using README.md examples\n")
cat("  4. Update analysis scripts to use app/2023-24-25/ databases\n")
cat("\n")
cat("Quick test:\n")
cat("  Rscript -e 'readRDS(\"app/2023-24-25/ffa_db.rds\")$ffa_projtable %>% dplyr::distinct(season)'\n")
cat("\n")
