#!/usr/bin/env Rscript
# ==============================================================================
# Validate Unified Database Against Schema Specifications
# ==============================================================================
#
# Purpose: Verify that app/2023-24-25/ matches app_DATAMODEL.md and
#          app_DATA_DICTIONARY.md specifications
#
# Author: Generated by Claude Code
# Date: 2026-03-07
# ==============================================================================

library(tidyverse)
library(dm)
library(glue)

cat("\n")
cat("╔══════════════════════════════════════════════════════════════╗\n")
cat("║  Schema Validation: app/2023-24-25/                          ║\n")
cat("╚══════════════════════════════════════════════════════════════╝\n")
cat("\n")

DATA_DIR <- "app/2023-24-25"

# Track validation results
validation_results <- list()
issues_found <- list()

# Helper function to record validation
validate <- function(test_name, condition, expected, actual, severity = "ERROR") {
  status <- if (condition) "PASS" else severity

  validation_results[[test_name]] <<- list(
    status = status,
    expected = expected,
    actual = actual
  )

  if (!condition) {
    issues_found[[length(issues_found) + 1]] <<- list(
      test = test_name,
      severity = severity,
      expected = expected,
      actual = actual
    )
  }

  return(condition)
}

# ==============================================================================
# 1. Load All Databases
# ==============================================================================

cat("──────────────────────────────────────────────────────────────\n")
cat("📂 Loading Databases\n")
cat("──────────────────────────────────────────────────────────────\n")

tryCatch({
  ffa_db <- readRDS(file.path(DATA_DIR, "ffa_db.rds"))
  cat("  ✓ ffa_db.rds loaded\n")
}, error = function(e) {
  cat("  ❌ Failed to load ffa_db.rds:", e$message, "\n")
  quit(status = 1)
})

tryCatch({
  nfl_teams_db <- readRDS(file.path(DATA_DIR, "nfl_teams_db.rds"))
  cat("  ✓ nfl_teams_db.rds loaded\n")
}, error = function(e) {
  cat("  ❌ Failed to load nfl_teams_db.rds:", e$message, "\n")
})

tryCatch({
  nfl_players_db <- readRDS(file.path(DATA_DIR, "nfl_players_db.rds"))
  cat("  ✓ nfl_players_db.rds loaded\n")
}, error = function(e) {
  cat("  ❌ Failed to load nfl_players_db.rds:", e$message, "\n")
})

tryCatch({
  nfl_stats_db <- readRDS(file.path(DATA_DIR, "nfl_stats_db.rds"))
  cat("  ✓ nfl_stats_db.rds loaded\n")
}, error = function(e) {
  cat("  ❌ Failed to load nfl_stats_db.rds:", e$message, "\n")
})

tryCatch({
  nfl_round_db <- readRDS(file.path(DATA_DIR, "nfl_round_db.rds"))
  cat("  ✓ nfl_round_db.rds loaded\n")
}, error = function(e) {
  cat("  ❌ Failed to load nfl_round_db.rds:", e$message, "\n")
})

tryCatch({
  nfl_recap_db <- readRDS(file.path(DATA_DIR, "nfl_recap_db.rds"))
  cat("  ✓ nfl_recap_db.rds loaded\n")
}, error = function(e) {
  cat("  ❌ Failed to load nfl_recap_db.rds:", e$message, "\n")
})

tryCatch({
  dudes_sim_db <- readRDS(file.path(DATA_DIR, "dudes_simulation_db.rds"))
  cat("  ✓ dudes_simulation_db.rds loaded\n")
}, error = function(e) {
  cat("  ❌ Failed to load dudes_simulation_db.rds:", e$message, "\n")
})

cat("\n")

# ==============================================================================
# 2. Validate ffa_db.rds
# ==============================================================================

cat("──────────────────────────────────────────────────────────────\n")
cat("📊 Validating ffa_db.rds\n")
cat("──────────────────────────────────────────────────────────────\n")

# Extract tables
ffa_tables <- dm_get_tables(ffa_db)

# 2.1 Table existence
validate("ffa_db: table count",
         length(ffa_tables) == 5,
         "5 tables",
         paste(length(ffa_tables), "tables"))

expected_tables <- c("ffa_player_ids", "ffa_players", "ffa_projtable",
                     "ffa_proj_source_points", "ffa_scrape")
actual_tables <- names(ffa_tables)

for (tbl in expected_tables) {
  validate(paste0("ffa_db: ", tbl, " exists"),
           tbl %in% actual_tables,
           "Table exists",
           if (tbl %in% actual_tables) "Present" else "Missing")
}

# 2.2 ffa_player_ids structure
if ("ffa_player_ids" %in% names(ffa_tables)) {
  player_ids <- ffa_tables$ffa_player_ids

  # Expected 15 columns (after 2025 schema)
  validate("ffa_player_ids: column count",
           ncol(player_ids) == 15,
           "15 columns",
           paste(ncol(player_ids), "columns"))

  # Check key columns
  expected_cols <- c("id", "nfl_id", "stats_id", "gsis_id", "sleeper_id")
  for (col in expected_cols) {
    validate(paste0("ffa_player_ids: ", col),
             col %in% names(player_ids),
             "Column exists",
             if (col %in% names(player_ids)) "Present" else "Missing")
  }

  # Check data types
  validate("ffa_player_ids: id is character",
           is.character(player_ids$id),
           "character",
           class(player_ids$id)[1])

  # Check for primary key uniqueness
  validate("ffa_player_ids: id is unique",
           n_distinct(player_ids$id) == nrow(player_ids),
           paste(nrow(player_ids), "unique IDs"),
           paste(n_distinct(player_ids$id), "unique IDs"))
}

# 2.3 ffa_projtable structure
if ("ffa_projtable" %in% names(ffa_tables)) {
  projtable <- ffa_tables$ffa_projtable

  # Check seasons
  seasons <- projtable %>% distinct(season) %>% pull() %>% sort()
  validate("ffa_projtable: seasons 2023-2025",
           all(c(2023, 2024, 2025) %in% seasons),
           "2023, 2024, 2025",
           paste(seasons, collapse = ", "))

  # Check key columns exist
  key_cols <- c("season", "week", "tag", "timestamp", "avg_type", "id", "pos", "points")
  for (col in key_cols) {
    validate(paste0("ffa_projtable: ", col),
             col %in% names(projtable),
             "Column exists",
             if (col %in% names(projtable)) "Present" else "Missing")
  }

  # Check data types
  validate("ffa_projtable: season is integer",
           is.integer(projtable$season),
           "integer",
           class(projtable$season)[1])

  validate("ffa_projtable: points is numeric",
           is.numeric(projtable$points),
           "numeric",
           class(projtable$points)[1])

  validate("ffa_projtable: timestamp is POSIXct",
           inherits(projtable$timestamp, "POSIXct"),
           "POSIXct",
           class(projtable$timestamp)[1])

  # Check for new columns (2025 schema)
  new_cols <- c("first_name", "last_name", "team", "position", "age", "exp")
  validate("ffa_projtable: has 2025 player metadata columns",
           all(new_cols %in% names(projtable)),
           paste(new_cols, collapse = ", "),
           paste(intersect(new_cols, names(projtable)), collapse = ", "))

  # Check VOR columns removed (2023 legacy)
  vor_cols <- c("points_vor", "floor_vor", "ceiling_vor")
  validate("ffa_projtable: VOR columns removed",
           !any(vor_cols %in% names(projtable)),
           "No VOR columns",
           if (any(vor_cols %in% names(projtable)))
             paste("Found:", paste(intersect(vor_cols, names(projtable)), collapse = ", "))
           else "No VOR columns")
}

cat("\n")

# ==============================================================================
# 3. Validate nfl_stats_db.rds (Special: Schema Version)
# ==============================================================================

cat("──────────────────────────────────────────────────────────────\n")
cat("📊 Validating nfl_stats_db.rds\n")
cat("──────────────────────────────────────────────────────────────\n")

stats_tables <- dm_get_tables(nfl_stats_db)

# 3.1 nfl_players_adv_stats - CRITICAL TEST
if ("nfl_players_adv_stats" %in% names(stats_tables)) {
  adv_stats <- stats_tables$nfl_players_adv_stats

  # Check schema_version column exists
  validate("nfl_players_adv_stats: schema_version exists",
           "schema_version" %in% names(adv_stats),
           "schema_version column",
           if ("schema_version" %in% names(adv_stats)) "Present" else "Missing")

  if ("schema_version" %in% names(adv_stats)) {
    # Check both versions present
    versions <- adv_stats %>% distinct(schema_version) %>% pull() %>% sort()

    validate("nfl_players_adv_stats: has both 2023 and 2025 versions",
             all(c("2023", "2025") %in% versions),
             "2023, 2025",
             paste(versions, collapse = ", "))

    # Count rows per version
    version_counts <- adv_stats %>% count(schema_version)
    cat("\n  Schema version distribution:\n")
    print(version_counts)
    cat("\n")

    # Check 2023-specific columns
    cols_2023 <- adv_stats %>%
      filter(schema_version == "2023") %>%
      select(where(~!all(is.na(.)))) %>%
      names()

    # Check 2025-specific columns
    cols_2025 <- adv_stats %>%
      filter(schema_version == "2025") %>%
      select(where(~!all(is.na(.)))) %>%
      names()

    unique_2023 <- setdiff(cols_2023, cols_2025)
    unique_2025 <- setdiff(cols_2025, cols_2023)

    cat("  2023-only columns:", paste(unique_2023, collapse = ", "), "\n")
    cat("  2025-only columns:", paste(unique_2025, collapse = ", "), "\n")

    # Verify schema_note exists
    validate("nfl_players_adv_stats: schema_note exists",
             "schema_note" %in% names(adv_stats),
             "schema_note column",
             if ("schema_note" %in% names(adv_stats)) "Present" else "Missing",
             "WARNING")
  }
}

# 3.2 nfl_players_points - Check season coverage
if ("nfl_players_points" %in% names(stats_tables)) {
  points <- stats_tables$nfl_players_points

  seasons <- points %>% distinct(season) %>% pull() %>% sort()

  validate("nfl_players_points: includes 2023-2025",
           all(c(2023, 2024, 2025) %in% seasons),
           "At least 2023-2025",
           paste(seasons, collapse = ", "))

  # Count by season
  season_counts <- points %>% count(season) %>% arrange(season)
  cat("\n  Season distribution:\n")
  print(season_counts)
  cat("\n")
}

cat("\n")

# ==============================================================================
# 4. Validate dudes_simulation_db.rds (List Columns)
# ==============================================================================

cat("──────────────────────────────────────────────────────────────\n")
cat("📊 Validating dudes_simulation_db.rds\n")
cat("──────────────────────────────────────────────────────────────\n")

sim_tables <- dm_get_tables(dudes_sim_db)

# 4.1 dudes_players_seeds
if ("dudes_players_seeds" %in% names(sim_tables)) {
  seeds <- sim_tables$dudes_players_seeds

  # Check list column
  validate("dudes_players_seeds: seeds is list",
           is.list(seeds$seeds),
           "list column",
           class(seeds$seeds)[1])

  # Check no NULL values in list
  null_count <- sum(sapply(seeds$seeds, is.null))
  validate("dudes_players_seeds: no NULL in seeds",
           null_count == 0,
           "0 NULL values",
           paste(null_count, "NULL values"),
           if (null_count > 0) "WARNING" else "PASS")

  # Sample a few list elements
  if (nrow(seeds) > 0) {
    sample_lengths <- seeds %>%
      slice_head(n = 5) %>%
      mutate(seed_length = map_int(seeds, length)) %>%
      pull(seed_length)

    cat("  Sample seed lengths:", paste(sample_lengths, collapse = ", "), "\n")
  }
}

# 4.2 dudes_players_simulations
if ("dudes_players_simulations" %in% names(sim_tables)) {
  sims <- sim_tables$dudes_players_simulations

  # Check list columns
  validate("dudes_players_simulations: simulations is list",
           "simulations" %in% names(sims) && is.list(sims$simulations),
           "list column",
           if ("simulations" %in% names(sims)) class(sims$simulations)[1] else "Missing")

  validate("dudes_players_simulations: simQuantiles is list",
           "simQuantiles" %in% names(sims) && is.list(sims$simQuantiles),
           "list column",
           if ("simQuantiles" %in% names(sims)) class(sims$simQuantiles)[1] else "Missing")

  # Check simQuantiles structure
  if ("simQuantiles" %in% names(sims) && nrow(sims) > 0) {
    sample_quantiles <- sims$simQuantiles[[1]]

    if (is.list(sample_quantiles)) {
      cat("  Sample simQuantiles structure:\n")
      cat("    Names:", paste(names(sample_quantiles), collapse = ", "), "\n")

      expected_quantiles <- c("q05", "q15", "q30", "q50", "q70", "q85", "q95")

      # Check if it's in the expected format
      if (all(c("name", "value") %in% names(sample_quantiles))) {
        cat("    Format: name-value pairs (nested list)\n")
      } else if (any(expected_quantiles %in% names(sample_quantiles))) {
        cat("    Format: named numeric vector\n")
      }
    }
  }

  # Check seasons
  seasons <- sims %>% distinct(season) %>% pull() %>% sort()
  validate("dudes_players_simulations: includes expected seasons",
           all(seasons >= 2023),
           "2023+",
           paste(seasons, collapse = ", "))
}

cat("\n")

# ==============================================================================
# 5. Validate Primary Keys
# ==============================================================================

cat("──────────────────────────────────────────────────────────────\n")
cat("🔑 Validating Primary Keys\n")
cat("──────────────────────────────────────────────────────────────\n")

# Test primary key uniqueness for key tables
test_pk <- function(db_name, table_name, pk_cols) {
  tables <- dm_get_tables(get(db_name))

  if (table_name %in% names(tables)) {
    tbl <- tables[[table_name]]

    # Check columns exist
    missing_cols <- setdiff(pk_cols, names(tbl))
    if (length(missing_cols) > 0) {
      cat("  ⚠️  ", db_name, "$", table_name, ": Missing PK columns: ",
          paste(missing_cols, collapse = ", "), "\n", sep = "")
      return(FALSE)
    }

    # Check uniqueness
    # Handle NA values in PKs
    has_na <- tbl %>%
      select(all_of(pk_cols)) %>%
      summarise(across(everything(), ~sum(is.na(.)))) %>%
      summarise(total = sum(c_across(everything()))) %>%
      pull(total)

    if (has_na > 0) {
      validate(paste0(db_name, "$", table_name, ": PK has no NAs"),
               FALSE,
               "0 NAs",
               paste(has_na, "NAs in PK columns"),
               "WARNING")
    }

    # Count distinct vs total
    distinct_count <- tbl %>%
      distinct(across(all_of(pk_cols))) %>%
      nrow()

    total_count <- nrow(tbl)

    validate(paste0(db_name, "$", table_name, ": PK uniqueness"),
             distinct_count == total_count,
             paste(total_count, "rows =", total_count, "unique"),
             paste(total_count, "rows =", distinct_count, "unique"))

    if (distinct_count != total_count) {
      duplicates <- total_count - distinct_count
      cat("  ❌ ", duplicates, " duplicate PK combinations found\n", sep = "")
    } else {
      cat("  ✓ ", db_name, "$", table_name, ": PK unique (",
          format(total_count, big.mark = ","), " rows)\n", sep = "")
    }

    return(distinct_count == total_count)
  } else {
    cat("  ⚠️  Table not found: ", db_name, "$", table_name, "\n", sep = "")
    return(FALSE)
  }
}

# Test key primary keys
test_pk("ffa_db", "ffa_player_ids", "id")
test_pk("ffa_db", "ffa_players", c("id", "pos"))
test_pk("ffa_db", "ffa_projtable",
        c("season", "week", "tag", "timestamp", "avg_type", "id", "pos"))
test_pk("nfl_players_db", "nfl_players", "playerId")
test_pk("nfl_stats_db", "nfl_players_points", c("playerId", "season", "week"))
test_pk("dudes_sim_db", "dudes_players_seeds",
        c("season", "week", "id", "playerId", "pos", "simType"))

cat("\n")

# ==============================================================================
# 6. Summary Report
# ==============================================================================

cat("──────────────────────────────────────────────────────────────\n")
cat("📋 Validation Summary\n")
cat("──────────────────────────────────────────────────────────────\n")

# Count results
passed <- sum(sapply(validation_results, function(x) x$status == "PASS"))
warnings <- sum(sapply(validation_results, function(x) x$status == "WARNING"))
errors <- sum(sapply(validation_results, function(x) x$status == "ERROR"))
total <- length(validation_results)

cat("\n")
cat("Total tests run:", total, "\n")
cat("  ✅ Passed:  ", passed, "\n", sep = "")
if (warnings > 0) {
  cat("  ⚠️  Warnings:", warnings, "\n", sep = "")
}
if (errors > 0) {
  cat("  ❌ Errors:  ", errors, "\n", sep = "")
}
cat("\n")

# List issues
if (length(issues_found) > 0) {
  cat("Issues Found:\n")
  cat("─────────────\n")
  for (issue in issues_found) {
    icon <- if (issue$severity == "WARNING") "⚠️ " else "❌"
    cat(icon, " ", issue$test, "\n", sep = "")
    cat("   Expected: ", issue$expected, "\n", sep = "")
    cat("   Actual:   ", issue$actual, "\n", sep = "")
    cat("\n")
  }
} else {
  cat("✨ No issues found! All validations passed.\n\n")
}

# Final verdict
cat("──────────────────────────────────────────────────────────────\n")
if (errors == 0) {
  cat("✅ VERDICT: Schema is COMPLIANT with specifications\n")
  if (warnings > 0) {
    cat("   (with ", warnings, " minor warnings)\n", sep = "")
  }
} else {
  cat("❌ VERDICT: Schema has ISSUES that need attention\n")
  cat("   (", errors, " errors, ", warnings, " warnings)\n", sep = "")
}
cat("──────────────────────────────────────────────────────────────\n")
cat("\n")

# Exit with appropriate code
if (errors > 0) {
  quit(status = 1)
} else {
  quit(status = 0)
}
